### PR TITLE
Add `readContent` and `readManifestContent` to read raw content

### PR DESCRIPTION
**Pull request by LegNeato**
I need to store the raw file content into a database in some cases...this lets me get at it.

### CODE REVIEW

**Comment by sorccu** [comment]
Let me think about this a bit, I feel that `readManifestContent()` is a bit unnecessary - perhaps we could just make `MANIFEST` accessible as ApkReader.MANIFEST and you could use it with `readContent()`. Not 100% sure if it should be called `readContent()` or something else, either.

**Comment by sorccu** [comment]
I think I just found a bug in the current apkreader... it's accidentally hardcoded to read nothing but the MANIFEST.

**Comment by LegNeato** [comment]
Sure, let me know what you want to do and I can change it (or feel free to just take edit the PR yourself!)

**Comment by sorccu** [comment]
I made some changes and added docs. Released as 2.1.0.

**Comment by LegNeato** [comment]
Great, thanks for the fast turnaround!

**Pull request merged**
