### PR TITLE
added method to extract apk supported architectures

### PR DESCRIPTION
**Pull request by id0Sch**
hope you find this acceptable,
thanks

### CODE REVIEW

**Comment by id0Sch** [comment]
can you please merge it this week? 
i have a version release that depends on that feature :)

**Comment by sorccu** [comment]
I have a few comments, but first, do you have an example .apk you could provide for testing?

**Comment by id0Sch** [comment]
almost every apk is valid for these tests,
i do have one - where should I put it? tests directory?

**Comment by sorccu** [comment]
Could you post it here into this issue, I think you can just drag and drop. I'll try to use it as a fixture for tests. It should be one that doesn't contain anyone's intellectual property.

**Comment by id0Sch** [comment]
i have a random app from google-play is that ok?

**Comment by sorccu** [comment]
Not really... they could issue a DMCA takedown request for this whole repository if we added it here.

**Comment by id0Sch** [comment]
so...what should i do ? :)

**Comment by id0Sch** [comment]
still waiting for further instructions

**Pull request closed without merging**
